language: generic 
services:
    - docker
before-install:
    - docker build -t naveenvadlamudi176/frontend -f Dockerfile.dev .
script:
    - docker run -e CI=true naveenvadlamudi176/frontend npm run test -- --coverage
deploy:
    provider: elastibeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: " DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-453372923028"
    bucket_path: "docker-react"
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY  
